import '@material/web/list/list.js';
import '@material/web/list/list-item.js';

export function RecipeList() {
    return (
        <md-list>
            <md-list-item>
                Pizza
            </md-list-item>
            <md-list-item>
                Pasta
            </md-list-item>
            <md-list-item>
                Pizza
            </md-list-item>
            <md-list-item>
                Pasta
            </md-list-item>
            <md-list-item>
                Pizza
            </md-list-item>
            <md-list-item>
                Pasta
            </md-list-item>
            <md-list-item>
                Pizza
            </md-list-item>
            <md-list-item>
                Pasta
            </md-list-item>
            <md-list-item>
                Pizza
            </md-list-item>
            <md-list-item>
                Pasta
            </md-list-item>
            <md-list-item>
                Pizza
            </md-list-item>
            <md-list-item>
                Pasta
            </md-list-item>
            <md-list-item>
                Pizza
            </md-list-item>
            <md-list-item>
                Pasta
            </md-list-item>
            <md-list-item>
                Pizza
            </md-list-item>
            <md-list-item>
                Pasta
            </md-list-item>
            <md-list-item>
                Pizza
            </md-list-item>
            <md-list-item>
                Pasta
            </md-list-item>
            <md-list-item>
                Pizza
            </md-list-item>
            <md-list-item>
                Pasta
            </md-list-item>
        </md-list>
    )
}
