version: "3.8"
name: "recipedex"
services:

  backend:
    build:
      context:
        ../backend
      dockerfile:
        Dockerfile
    image: python/backend
    command: uvicorn api.api:api --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000

  frontend:
    build:
      context:
        ../frontend
      dockerfile:
        Dockerfile
    image: node/frontend
    ports:
      - 80:80
