from setuptools import setup
from setuptools import find_packages

setup(
    name='recipedex',
    version='1.0.0',
    description='Automatically parse and extract info from recipes.',
    author='Edward Gorman',
    author_email='',
    packages=find_packages('.'),
    install_requires=[
        "attrs",
        "autopep8",
        "beautifulsoup4",
        "certifi",
        "charset-normalizer",
        "click",
        "colorama",
        "coverage",
        "exceptiongroup",
        "extruct",
        "flake8",
        "html-text",
        "html5lib",
        "isodate",
        "joblib",
        "jstyleson",
        "lxml",
        "mccabe",
        "mf2py",
        "numpy",
        "parse-ingredients",
        "pluggy",
        "pycodestyle",
        "pyflakes",
        "pyparsing",
        "pyRdfa3",
        "pytest",
        "pytest-cov",
        "rdflib",
        "recipe-scrapers",
        "regex",
        "requests",
        "six",
        "tomli",
        "tqdm",
        "urllib3",
        "w3lib",
        "webencodings",
    ]
)
