import os
from internal.config import CONFIG_DIRECTORY


PROJECT_ID = os.getenv("GCP_CLOUD_PROJECT")
PROJECT_REGION = os.getenv("GCP_CLOUD_REGION")
FIREBASE_CONFIG_FILEPATH = os.path.join(CONFIG_DIRECTORY, "firebase.json")

ARTIFACT_GCS_BUCKET = os.getenv("GCP_ARTIFACT_GCS_BUCKET")
MEMORY_RAG_CORPUS_ID = os.getenv("GCP_MEMORY_RAG_CORPUS_ID")
MEMORY_RAG_CORPUS_PATH = f"projects/{PROJECT_ID}/locations/{PROJECT_REGION}/ragCorpora/{MEMORY_RAG_CORPUS_ID}"
