import os


STORAGE_PROJECT_ID = os.getenv("GCP_PROJECT_ID")
STORAGE_RECIPE_NAME = os.getenv("STORAGE_RECIPE_NAME")
STORAGE_RECIPE_VERSION = os.getenv("STORAGE_RECIPE_VERSION")
STORAGE_USER_NAME = os.getenv("STORAGE_USER_NAME")
STORAGE_USER_VERSION = os.getenv("STORAGE_USER_VERSION")
