import os


STORAGE_PROJECT_ID = os.getenv("GCP_PROJECT_ID")
STORAGE_DATABASE_NAME = os.getenv("STORAGE_DATABASE_NAME")
STORAGE_COLLECTION_RECIPE_NAME = os.getenv("STORAGE_COLLECTION_RECIPE_NAME")
STORAGE_COLLECTION_USER_NAME = os.getenv("STORAGE_COLLECTION_USER_NAME")
