name: App Push Event

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "app/**"
      - ".github/workflows/app-push.yaml"

jobs:
  deploy-live:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: live
          projectId: ${{ secrets.TF_VAR_GCP_PROJECT_ID }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
