name: Backend Pull Request Event

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "backend/**"
      - ".github/workflows/backend-pull-request.yaml"

jobs:
  backend-build:
    name: Backend Build
    uses: ./.github/workflows/backend-build.yaml
    with:
      environment: ${{ github.base_ref == 'main' && 'prod' || 'dev' }}

  deploy-preview:
    name: Deploy Preview
    needs: backend-build
    uses: ./.github/workflows/backend-deploy.yaml
    with:
      environment: ${{ github.base_ref == 'main' && 'prod' || 'dev' }}
      service_suffix: -pr-${{ github.event.pull_request.base.sha }}
      image_tag: ${{ github.sha }}
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_PROJECT_REGION: ${{ secrets.GCP_PROJECT_REGION }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  comment-preview:
    name: Comment Preview
    needs: deploy-preview
    runs-on: ubuntu-latest
    if: ${{ needs.deploy-preview.result == 'success' }}
    steps:
      - id: find
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Create or Update Action

      - id: sha
        uses: benjlevesque/short-sha@v3.0

      - id: comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Visit the preview URL for this PR (updated for commit ${{ steps.sha.outputs.sha }}):

            ${{ needs.deploy-preview.outputs.deploy-url }}

            <sub>(expires when the PR is closed)</sub>

            <sub>🔥 via [Create or Update Action](https://github.com/peter-evans/create-or-update-comment) 🧑‍💻</sub>
          edit-mode: replace

  github-cleanup:
    name: GitHub Cleanup
    uses: ./.github/workflows/github-cleanup.yaml
    needs: deploy-preview
    if: ${{ always() }}
    with:
      github_sha_head: ${{ github.event.pull_request.head.sha }}
