name: Backend Build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      python-version:
        required: false
        default: '3.13'
        type: string
    outputs:
      artifact-name:
        description: 'The name of the uploaded artifact'
        value: backend

jobs:
  backend-build:
    name: Backend Build
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - id: config
        run: |
          mkdir -p backend/internal/config
          echo '${{ secrets.FIREBASE_APP_CONFIG }}' > backend/internal/config/firebase.json
          echo 'SERVICE_ALLOWED_ORIGIN=https://${{ secrets.GCP_PROJECT_ID }}.web.app' > backend/.env

      - id: run
        run: |
          make backend-install
          make backend-lint
          make backend-test
          make backend-build-service OUTPUT=backend.tar

      - id: upload
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend.tar
