name: Backend Push Event

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "backend/**"
      - ".github/workflows/backend-push.yaml"

jobs:
  backend-build:
    name: Backend Build
    uses: ./.github/workflows/backend-build.yaml

  deploy-live:
    name: Deploy Live
    needs: backend-build
    uses: ./.github/workflows/backend-deploy.yaml
    with:
      environment: ${{ github.base_ref == 'main' && 'prod' || 'dev' }}
      image_tag: ${{ github.sha }}
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_PROJECT_REGION: ${{ secrets.GCP_PROJECT_REGION }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  github-cleanup:
    name: GitHub Cleanup
    uses: ./.github/workflows/github-cleanup.yaml
    needs: deploy-live
    if: ${{ always() }}
    with:
      github_sha_head: ${{ github.sha }}
