name: Backend Pull Request Event

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "backend/**"
      - ".github/workflows/backend-pull-request.yaml"

jobs:
  backend-build:
    name: Backend Build
    uses: ./.github/workflows/backend-build.yaml

  deploy-preview:
    name: Deploy Preview
    needs: backend-build
    uses: ./.github/workflows/backend-deploy.yaml
    with:
      environment: ${{ github.base_ref == 'main' && 'prod' || 'dev' }}
      service_suffix: -pr-${{ github.event.pull_request.base.sha }}
      image_tag: ${{ github.sha }}
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_PROJECT_REGION: ${{ secrets.GCP_PROJECT_REGION }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  github-cleanup:
    name: GitHub Cleanup
    uses: ./.github/workflows/github-cleanup.yaml
    needs: deploy-preview
    if: ${{ always() }}
    with:
      github_sha_head: ${{ github.event.pull_request.head.sha }}
