name: GitHub Cleanup

on:
  workflow_call:
    inputs:
      github_sha_head:
        required: true
        type: string

jobs:
  delete-deployments:
    name: Delete Deployments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          GITHUB_SHA_HEAD: ${{ inputs.github_sha_head }}
        with:
          script: |
            const { GITHUB_SHA_HEAD } = process.env;
            const deployments = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: GITHUB_SHA_HEAD
            });
            await Promise.all(
              deployments.data.map(async (deployment) => {
                await github.rest.repos.createDeploymentStatus({ 
                  owner: context.repo.owner, 
                  repo: context.repo.repo, 
                  deployment_id: deployment.id, 
                  state: 'inactive' 
                });
                return github.rest.repos.deleteDeployment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: deployment.id
                });
              })
            );
