
name: RecipeDex CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - name: Checkout RecipeDex repository
      uses: actions/checkout@v3

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.6'
    
    - name: Install modules
      run: |
        python -m pip install recipedex/.
        python -m pip install backend/.

    - name: Lint with flake8
      run: |
        python -m flake8 backend/. --max-line-length=120
        python -m flake8 recipedex/. --max-line-length=120
    
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install packages
      run: |
        npm install --prefix frontend

    - name: Lint with eslint
      run: |
        npm run lint --prefix frontend

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - name: Checkout RecipeDex repository
      uses: actions/checkout@v3

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.6'
      
    - name: Install modules
      run: |
        python -m pip install recipedex/.
        python -m pip install backend/.

    - name: Test with pytest
      run: |
        python -m pytest -svv backend/tests/ --disable-pytest-warnings --cov=backend --cov-config=backend/tests/.coveragerc
        python -m pytest -svv recipedex/tests/ --disable-pytest-warnings --cov=recipedex --cov-config=recipedex/tests/.coveragerc
    
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install packages
      run: |
        npm install --prefix frontend

    - name: Test with jest
      run: |
        CI=true npm run test --prefix frontend
