# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: RecipeDex CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CACHE_NUMBER: 0

permissions:
  contents: read

stages:
  - lint
  - test

lint_python:
  stage: lint
  image: python:3.9
  before_script: 
    - python -m pip install backend
    - python -m pip install recipedex
  script:
    - python -m flake8 backend/. --max-line-length=120
    - python -m flake8 recipedex/. --max-line-length=120

test_python:
  stage: test
  image: python:3.9
  before_script:
    - python -m pip install backend
    - python -m pip install recipedex
  script:
    - python -m pytest -svv backend/tests/ --disable-pytest-warnings --cov=backend --cov-config=backend/tests/.coveragerc
    - python -m pytest -svv recipedex/tests/ --disable-pytest-warnings --cov=recipedex --cov-config=recipedex/tests/.coveragerc
