name: Pull Request Close Dev

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  cleanup-preview:
    name: Cleanup Preview
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - id: authenticate
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - id: setup
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - id: cleanup
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_PROJECT_REGION }}-docker.pkg.dev
          gcloud run services delete "backend-pr-${{ github.event.pull_request.base.sha }}" --region="${{ secrets.GCP_PROJECT_REGION }}" --quiet
          gcloud docker images --filter "reference=*:pr-${{ github.event.pull_request.base.sha }}" -q | xargs -r docker rmi

  github-cleanup:
    name: GitHub Cleanup
    needs: [cleanup-preview]
    if: always()

    uses: ./.github/workflows/github-cleanup.yaml
    with:
      github_sha_head: ${{ github.event.pull_request.head.sha }}
