name: Pull Request Close Dev

env:
  environment: dev

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  cleanup-preview:
    name: Cleanup Preview
    runs-on: ubuntu-latest
    environment: ${{ env.environment }}

    steps:
      - id: authenticate
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - id: setup
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - id: cleanup
        run: |
          SERVICE_NAME="backend-pr-${{ github.event.pull_request.base.sha }}"
          gcloud run services delete "$SERVICE_NAME" --region="${{ secrets.GCP_PROJECT_REGION }}" --quiet || echo "Service $SERVICE_NAME not found or already deleted."

  github-cleanup:
    name: GitHub Cleanup
    uses: ./.github/workflows/github-cleanup.yaml
    needs: cleanup-preview
    if: ${{ always() }}
    with:
      github_sha_head: ${{ github.event.pull_request.head.sha }}
