name: Push Commit Dev Event

env:
  environment: dev

on:
  push:
    branches:
      - develop

jobs:
  github-changes:
    name: GitHub Changes
    uses: ./.github/workflows/github-changes.yaml

  infrastructure-deploy:
    name: Infrastructure Deploy
    needs: github-changes
    if: needs.github-changes.infrastructure == 'true'

    uses: ./.github/workflows/infrastructure-plan.yaml
    with:
      environment: ${{ inputs.environment }}
      apply_plan: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
      TF_VAR_GCP_PROJECT_ID: ${{ secrets.TF_VAR_GCP_PROJECT_ID }}
      TF_VAR_GCP_PROJECT_REGION: ${{ secrets.TF_VAR_GCP_PROJECT_REGION }}
      TF_VAR_GCP_PROJECT_ZONE: ${{ secrets.TF_VAR_GCP_PROJECT_ZONE }}

  backend-build:
    name: Backend Build
    needs: github-changes
    if: needs.github-changes.backend == 'true'

    uses: ./.github/workflows/backend-build.yaml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      FIREBASE_APP_CONFIG: ${{ secrets.FIREBASE_APP_CONFIG }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

  backend-deploy:
    name: Backend Deploy
    needs: [backend-build, infrastructure-deploy]

    uses: ./.github/workflows/backend-deploy.yaml
    with:
      environment: ${{ inputs.environment }}
      image_tag: ${{ github.sha }}
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_PROJECT_REGION: ${{ secrets.GCP_PROJECT_REGION }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  frontend-build:
    name: Frontend Build
    needs: backend-deploy
    if: needs.github-changes.frontend == 'true' || needs.backend-deploy.result

    uses: ./.github/workflows/frontend-build.yaml
    secrets:
      FIREBASE_APP_CONFIG: ${{ secrets.FIREBASE_APP_CONFIG }}
      BACKEND_API: ${{ (needs.backend-deploy.result == 'success' && needs.backend-deploy.outputs.backend-api) || secrets.BACKEND_API }}

  frontend-deploy:
    name: Frontend Deploy
    needs: frontend-build
    if: needs.github-changes.frontend == 'true' || needs.backend-deploy.result

    uses: ./.github/workflows/frontend-deploy.yaml
    with:
      apply_live: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FIREBASE_GCP_PROJECT_ID: ${{ secrets.FIREBASE_GCP_PROJECT_ID }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

  github-cleanup:
    name: GitHub Cleanup
    uses: ./.github/workflows/github-cleanup.yaml
    needs: [infrastructure-deploy, backend-deploy, frontend-deploy]
    if: always()
    with:
      github_sha_head: ${{ github.sha }}

